#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Tue Jul 21 10:16:35 GMT 2026
android.nonTransitiveRClass=false
org.gradle.daemon.idletimeout=10800000
systemProp.user.language=en
systemProp.user.country=US
org.gradle.daemon=true
org.gradle.parallel=true
android.injected.testOnly=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8 -XX\:+UseParallelGC -Dorg.gradle.warning.mode\=all
android.useAndroidX=true
android.enableJetifier=false
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
