package mod.hey.studios.moreblock;

import androidx.annotation.NonNull;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Generates compatible overloads for MoreBlock parameters that have a default value.
 * <p>
 * Java has no default parameters, so the real implementation keeps its full parameter list (exactly what
 * {@code Lx.getMoreBlockCode} generates, untouched) and every omitted-default combination becomes a tiny
 * overload that forwards to it:
 * <pre>
 * public void _signUser(final String _uid, final int _coins, final boolean _isNewAccount) { ...real body... }
 * public void _signUser(final String _uid, final boolean _isNewAccount) {
 *     _signUser(_uid, 0, _isNewAccount);
 * }
 * </pre>
 * The declaration is parsed back from the code {@code Lx} produced rather than rebuilt, so naming, modifiers
 * and parameter types always match. If anything about it is unexpected, no overloads are generated and the
 * original code is returned unchanged.
 */
public final class MoreBlockOverloads {
    private static final String EOL = "\r\n";
    /** Combinations grow as 2^n, so only the first few defaults (in parameter order) are used. */
    private static final int MAX_DEFAULTS = 8;
    private static final int MAX_OVERLOADS = 64;
    private static final Pattern DECLARATION = Pattern.compile("^public\\s+(.+?)\\s+(_\\w+)\\((.*)\\)\\s*\\{\\s*$");
    private static final Set<String> PRIMITIVES = new HashSet<>(Arrays.asList(
            "boolean", "byte", "short", "int", "long", "float", "double", "char"));

    private MoreBlockOverloads() {
    }

    /**
     * @param code the method generated by {@code Lx.getMoreBlockCode(blockName, spec, body)}
     * @return {@code code} followed by the overloads for the stored defaults; {@code code} itself if the
     * MoreBlock has no (valid) defaults, as for every project created before this feature existed.
     */
    @NonNull
    public static String append(@NonNull String scId, @NonNull String javaName, @NonNull String blockName,
                                @NonNull String spec, @NonNull String code) {
        try {
            Map<String, String> defaults = MoreBlockDefaultsStore.get(scId, javaName, blockName, spec);
            if (defaults.isEmpty()) return code;
            String overloads = generate(code, defaults);
            return overloads.isEmpty() ? code : code + EOL + overloads;
        } catch (RuntimeException e) {
            return code; // never break code generation because of defaults
        }
    }

    private static final class Param {
        String declaration; // e.g. "final int _coins"
        String type;        // e.g. "int"
        String name;        // e.g. "_coins"
        String defaultExpression; // compile-valid Java expression, or null
    }

    /** @return the overload methods (each ending in EOL), or an empty string. */
    @NonNull
    static String generate(@NonNull String code, @NonNull Map<String, String> defaults) {
        int endOfHeader = code.indexOf('\n');
        if (endOfHeader < 0) return "";
        Matcher matcher = DECLARATION.matcher(code.substring(0, endOfHeader).trim());
        if (!matcher.matches()) return "";

        String returnType = matcher.group(1).trim();
        String methodName = matcher.group(2);
        List<Param> params = new ArrayList<>();
        for (String raw : splitTopLevel(matcher.group(3))) {
            String declaration = raw.trim();
            if (declaration.isEmpty()) continue;
            int lastSpace = declaration.lastIndexOf(' ');
            if (lastSpace < 0) return "";
            Param param = new Param();
            param.declaration = declaration;
            param.name = declaration.substring(lastSpace + 1);
            String type = declaration.substring(0, lastSpace).trim();
            if (type.startsWith("final ")) type = type.substring(6).trim();
            param.type = type;
            if (!param.name.matches("_\\w+") || type.isEmpty()) return "";

            MoreBlockDefaultValues.Kind kind = MoreBlockDefaultValues.kindForJavaType(type);
            String expression = defaults.get(param.name.substring(1));
            if (kind != null && expression != null && MoreBlockDefaultValues.isValidExpression(kind, expression)) {
                param.defaultExpression = expression;
            }
            params.add(param);
        }

        List<Integer> optional = new ArrayList<>();
        for (int i = 0; i < params.size() && optional.size() < MAX_DEFAULTS; i++) {
            if (params.get(i).defaultExpression != null) optional.add(i);
        }
        if (optional.isEmpty()) return "";

        // Candidate omit-sets: fewer omitted parameters first, and among equals the later (trailing) ones first.
        List<Integer> masks = new ArrayList<>();
        for (int mask = 1; mask < (1 << optional.size()); mask++) masks.add(mask);
        masks.sort((a, b) -> {
            int byCount = Integer.compare(Integer.bitCount(a), Integer.bitCount(b));
            return byCount != 0 ? byCount : Integer.compare(b, a);
        });

        List<String[]> accepted = new ArrayList<>();
        accepted.add(erasedTypes(params, Collections0.NONE));

        StringBuilder out = new StringBuilder();
        int generated = 0;
        for (int mask : masks) {
            if (generated >= MAX_OVERLOADS) break;

            Set<Integer> omitted = new HashSet<>();
            for (int bit = 0; bit < optional.size(); bit++) {
                if ((mask & (1 << bit)) != 0) omitted.add(optional.get(bit));
            }
            String[] signature = erasedTypes(params, omitted);
            if (!isUsable(signature, accepted)) continue;
            accepted.add(signature);

            StringBuilder declarationList = new StringBuilder();
            StringBuilder argumentList = new StringBuilder();
            for (int i = 0; i < params.size(); i++) {
                Param param = params.get(i);
                if (argumentList.length() > 0) argumentList.append(", ");
                if (omitted.contains(i)) {
                    argumentList.append(param.defaultExpression);
                } else {
                    if (declarationList.length() > 0) declarationList.append(", ");
                    declarationList.append(param.declaration);
                    argumentList.append(param.name);
                }
            }

            out.append("public ").append(returnType).append(' ').append(methodName)
                    .append('(').append(declarationList).append(") {").append(EOL)
                    .append("    ").append(returnType.equals("void") ? "" : "return ")
                    .append(methodName).append('(').append(argumentList).append(");").append(EOL)
                    .append('}').append(EOL);
            generated++;
            out.append(EOL);
        }

        // Jx trims the last two characters of the final MoreBlock; keep every method terminated by "}" + EOL.
        String result = out.toString();
        if (result.endsWith(EOL + EOL)) result = result.substring(0, result.length() - EOL.length());
        return result;
    }

    /** Parameter-type list (generics erased) after leaving out the given parameter indexes. */
    private static String[] erasedTypes(List<Param> params, Set<Integer> omitted) {
        List<String> types = new ArrayList<>();
        for (int i = 0; i < params.size(); i++) {
            if (!omitted.contains(i)) types.add(erase(params.get(i).type));
        }
        return types.toArray(new String[0]);
    }

    /**
     * A signature is rejected if it equals an existing one (same erasure is a compile error) or if it has the
     * same arity as an existing one and differs only in reference-typed positions, because a call passing
     * {@code null} for such a position would be ambiguous.
     */
    private static boolean isUsable(String[] candidate, List<String[]> accepted) {
        for (String[] other : accepted) {
            if (other.length != candidate.length) continue;
            boolean identical = true;
            boolean onlyReferenceDifferences = true;
            for (int i = 0; i < candidate.length; i++) {
                if (!candidate[i].equals(other[i])) {
                    identical = false;
                    if (PRIMITIVES.contains(candidate[i]) || PRIMITIVES.contains(other[i])) {
                        onlyReferenceDifferences = false;
                    }
                }
            }
            if (identical || onlyReferenceDifferences) return false;
        }
        return true;
    }

    static String erase(String type) {
        String erased = type;
        String previous;
        do {
            previous = erased;
            erased = erased.replaceAll("<[^<>]*>", "");
        } while (!erased.equals(previous));
        return erased.replace(" ", "");
    }

    /** Splits on commas that are not inside generic brackets (e.g. {@code HashMap<String, Object>}). */
    static List<String> splitTopLevel(String parameters) {
        List<String> parts = new ArrayList<>();
        int depth = 0;
        int start = 0;
        for (int i = 0; i < parameters.length(); i++) {
            char c = parameters.charAt(i);
            if (c == '<') depth++;
            else if (c == '>') depth--;
            else if (c == ',' && depth == 0) {
                parts.add(parameters.substring(start, i));
                start = i + 1;
            }
        }
        parts.add(parameters.substring(start));
        return parts;
    }

    private static final class Collections0 {
        static final Set<Integer> NONE = new HashSet<>();
    }
}
